// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQTq4aUIXk2BAgqH5RD3PbRatceSVhbg',
    appId: '1:1000589976875:web:21c0531cc407850376116e',
    messagingSenderId: '1000589976875',
    projectId: 'chat-app-ashir',
    authDomain: 'chat-app-ashir.firebaseapp.com',
    storageBucket: 'chat-app-ashir.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhvrxsZI9yU0O4LMT4BBzG17ScHABtkEM',
    appId: '1:1000589976875:android:3648a6076324cc4776116e',
    messagingSenderId: '1000589976875',
    projectId: 'chat-app-ashir',
    storageBucket: 'chat-app-ashir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKZAQShFZgeMUZgXGEYMUlMpdbdU85vQ',
    appId: '1:1000589976875:ios:a4f59cae6c5f349976116e',
    messagingSenderId: '1000589976875',
    projectId: 'chat-app-ashir',
    storageBucket: 'chat-app-ashir.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKZAQShFZgeMUZgXGEYMUlMpdbdU85vQ',
    appId: '1:1000589976875:ios:a4f59cae6c5f349976116e',
    messagingSenderId: '1000589976875',
    projectId: 'chat-app-ashir',
    storageBucket: 'chat-app-ashir.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjQTq4aUIXk2BAgqH5RD3PbRatceSVhbg',
    appId: '1:1000589976875:web:bc987a34a957a83376116e',
    messagingSenderId: '1000589976875',
    projectId: 'chat-app-ashir',
    authDomain: 'chat-app-ashir.firebaseapp.com',
    storageBucket: 'chat-app-ashir.firebasestorage.app',
  );
}
